server:
  error:
    include-stacktrace: never
  port: 9090
 
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always  
---  
spring:
  webflux.base-path: /api
  profiles:
    active: default
  
springdoc:
  pathsToMatch: /**
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/
    base-url: /  

springfox:
  documentation:
    swaggerUi:
      baseUrl: /documentation
    openApi:
      v3:
        path: /documentation/v3/api-docs
    swagger:
      v2:
        path: /documentation/v2/api-docs   
---
spring:
  profiles: default
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:
    
---
spring:
  profiles: test
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:          
      